server:
  port: 8090 #-- (ahí le explico profe) --#

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: ms_ventas
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/ventas/**
                
            - id: ms_catalogo
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/productos/**
                
            - id: ms_inventario
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/inventario/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/