spring.application.name=ms_catalogo

#-- puerto exclusivo de catalogo --#
server.port=8081

#-- supabase --#
spring.datasource.url=jdbc:postgresql://aws-1-us-west-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.pjryhukplrppfspdiftt
spring.datasource.password=TiendaBlinblineo12345*
spring.datasource.driver-class-name=org.postgresql.Driver
#-- limitar conexiones para no saturar Supabase --#
spring.datasource.hikari.maximum-pool-size=3

#-- jPA --#
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=bd_catalogo

#-- flyway --#
spring.flyway.enabled=true
spring.flyway.default-schema=bd_catalogo